# Generated by Django 3.0.2 on 2020-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_auto_20200929_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='genre',
            field=models.ManyToManyField(blank=True, to='my_blog.Genre'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_set', to='my_blog.User'),
        ),
    ]
