# Generated by Django 3.0.2 on 2020-09-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_auto_20200929_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
